# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  -

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'network_sandbox_jtudong'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az group create -l westus3 -n databricks-sandbox-rg
    failOnStandardError: true

#- task: AzureResourceManagerTemplateDeployment@3
#  inputs:
#    deploymentScope: 'Resource Group'
#    azureResourceManagerConnection: 'network_sandbox_jtudong'
#    subscriptionId: '17df786b-c9ea-4f50-9cb0-57b80e526f55'
#    action: 'Create Or Update Resource Group'
#    resourceGroupName: 'databricks-sandbox-rg'
#    location: 'West US 3'
#    templateLocation: 'URL of the file'
#    csmFileLink: 'https://raw.githubusercontent.com/jtudong/databricks-sandbox/development/databricks_deploy.json'
#    csmParametersFileLink: 'https://github.com/jtudong/databricks-sandbox/blob/development/databricks_deploy.parameters.json'
#    deploymentMode: 'Incremental'